name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x', '16.x']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Test
        env:
          CUSTOM_CERT_URL_TOKEN: ${{ secrets.CUSTOM_CERT_URL_TOKEN }}
          CUSTOM_PRIVATE_CERTS_URL: ${{ secrets.CUSTOM_PRIVATE_CERTS_URL }}
          CUSTOM_PUBLIC_CERTS_URL: ${{ secrets.CUSTOM_PUBLIC_CERTS_URL }}
        run: pnpm test
